name: Deploy Portfolio to Hostiman

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: portfolio-development-memory-system

    steps:

      - name: Проверка репозитория
        uses: actions/checkout@v4

      - name: Настройка Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: portfolio-development-memory-system/package-lock.json

      - name: Установка зависимостей
        run: npm install

      - name: Сборка проекта
        run: npm run build

      - name: Проверка dist
        run: |
          ls -la dist

      - name: Развертывание на FTP-сервере Hostiman
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:

          server: ${{ secrets.FTP_HOST }}

          username: ${{ secrets.FTP_USER }}

          password: ${{ secrets.FTP_PASSWORD }}

          server-dir: /www/vb-store.online/

          local-dir: portfolio-development-memory-system/dist/
